ARG K8S_VERSION="local"
ARG ETCD_VERSION="v3.5.17"
ARG HELM_VERSION="v3.17.3"
ARG KINE_VERSION="v0.13.14"
ARG KONNECTIVITY_VERSION="v0.32.0"

LABEL maintainer="vCluster Labs <support@vcluster.com>"
LABEL description="Kubernetes control plane components (apiserver, controller-manager, scheduler, etcd, konnectivity-server) and tar archives with node components"

FROM kubernetes-fips:${K8S_VERSION} AS k8s-local
FROM ghcr.io/loft-sh/etcd-fips:${ETCD_VERSION} AS etcd-fips
FROM ghcr.io/loft-sh/helm-fips:${HELM_VERSION} AS helm-fips
FROM ghcr.io/loft-sh/kine-fips:${KINE_VERSION} AS kine-fips
FROM ghcr.io/loft-sh/konnectivity-server-fips:${KONNECTIVITY_VERSION} AS konnectivity-fips

# we use the distroless base-nossl debug image, as it contains
# a basic shell, glibc and nothing else.
FROM gcr.io/distroless/base-nossl:debug

ARG K8S_VERSION="v1.33.0"

# Must be aligned with https://github.com/loft-sh/kubernetes/blob/main/Dockerfile#L30-L33
COPY --chown=kubernetes:kubernetes --from=k8s-local /kubernetes/kube-apiserver /kubernetes/kube-apiserver
COPY --chown=kubernetes:kubernetes --from=k8s-local /kubernetes/kube-controller-manager /kubernetes/kube-controller-manager
COPY --chown=kubernetes:kubernetes --from=k8s-local /kubernetes/kube-scheduler /kubernetes/kube-scheduler
COPY --chown=kubernetes:kubernetes --from=helm-fips /usr/local/bin/helm /kubernetes/helm
COPY --chown=kubernetes:kubernetes --from=etcd-fips /bin/etcd /kubernetes/etcd
COPY --chown=kubernetes:kubernetes --from=etcd-fips /bin/etcdctl /kubernetes/etcdctl
COPY --chown=kubernetes:kubernetes --from=kine-fips /bin/kine /kubernetes/kine
COPY --chown=kubernetes:kubernetes --from=konnectivity-fips /bin/konnectivity-server /kubernetes/konnectivity-server
COPY --chown=kubernetes:kubernetes ./kubernetes-${K8S_VERSION}-amd64-fips.tar.gz /kubernetes/kubernetes-${K8S_VERSION}-amd64.tar.gz
COPY --chown=kubernetes:kubernetes ./kubernetes-${K8S_VERSION}-arm64-fips.tar.gz /kubernetes/kubernetes-${K8S_VERSION}-arm64.tar.gz

# Set up the container
WORKDIR /
USER kubernetes
